target-version = "py39"
fix = true
src = ["./src/"]

[lint]
select = ["ALL"]
ignore = [
    "TD003", # Disable TODO issue
    "D100", # Missing docstring in public module
    "EXE002", # Use of `exec` statement
]

fixable = ["ALL"]